// <auto-generated />
using System;
using DataEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntity.Migrations
{
    [DbContext(typeof(SkladContext))]
    [Migration("20251119100218_005")]
    partial class _005
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataEntity.Data.Pokuty", b =>
                {
                    b.Property<int>("ID_Pokuta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Pokuta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Pokuta"));

                    b.Property<decimal>("Castka")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("DatumPokuty")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duvod")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ID_Pronajem")
                        .HasColumnType("int")
                        .HasColumnName("ID_Pronajem");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID_Pokuta");

                    b.HasIndex("ID_Pronajem");

                    b.ToTable("Pokuty");
                });

            modelBuilder.Entity("DataEntity.Data.Pronajmy", b =>
                {
                    b.Property<int>("ID_Pronajem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Pronajem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Pronajem"));

                    b.Property<decimal>("CenaCelkem")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<int>("DelkaDni")
                        .HasColumnType("int");

                    b.Property<int>("ID_Auto")
                        .HasColumnType("int")
                        .HasColumnName("ID_Auto");

                    b.Property<int>("ID_Zakaznik")
                        .HasColumnType("int")
                        .HasColumnName("ID_Zakaznik");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("ID_Pronajem");

                    b.HasIndex("ID_Auto");

                    b.HasIndex("ID_Zakaznik");

                    b.ToTable("Pronajmy");
                });

            modelBuilder.Entity("DataEntity.Data.Vozidla", b =>
                {
                    b.Property<int>("ID_Auto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Auto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Auto"));

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DenniSazba")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RokVyroby")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SPZ")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Stav")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("StavTachometru")
                        .HasColumnType("int");

                    b.Property<string>("Znacka")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Auto");

                    b.ToTable("Vozidla");
                });

            modelBuilder.Entity("DataEntity.Data.Zakaznici", b =>
                {
                    b.Property<int>("ID_Zakaznik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Zakaznik");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Zakaznik"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DatumNarozeni")
                        .HasColumnType("date");

                    b.Property<DateTime>("DatumVytvoreni")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PocetPronajmu")
                        .HasColumnType("int");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID_Zakaznik");

                    b.ToTable("Zakaznici");
                });

            modelBuilder.Entity("DataEntity.Data.Pokuty", b =>
                {
                    b.HasOne("DataEntity.Data.Pronajmy", "Pronajem")
                        .WithMany("Pokuty")
                        .HasForeignKey("ID_Pronajem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pronajem");
                });

            modelBuilder.Entity("DataEntity.Data.Pronajmy", b =>
                {
                    b.HasOne("DataEntity.Data.Vozidla", "Vozidlo")
                        .WithMany()
                        .HasForeignKey("ID_Auto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataEntity.Data.Zakaznici", "Zakaznik")
                        .WithMany()
                        .HasForeignKey("ID_Zakaznik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vozidlo");

                    b.Navigation("Zakaznik");
                });

            modelBuilder.Entity("DataEntity.Data.Pronajmy", b =>
                {
                    b.Navigation("Pokuty");
                });
#pragma warning restore 612, 618
        }
    }
}
